/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MacDots: typeof import('./src/components/MacDots.vue')['default']
    ProcessNodeCompress: typeof import('./src/components/ProcessNodeCompress.vue')['default']
    ProcessNodeDestination: typeof import('./src/components/ProcessNodeDestination.vue')['default']
    ProcessNodeScale: typeof import('./src/components/ProcessNodeScale.vue')['default']
    ProcessNodeSource: typeof import('./src/components/ProcessNodeSource.vue')['default']
  }
}
